import { docs } from "./docs.ts";

const baseURL = "https://css-hooks.com";

type Doc = (typeof docs)[number];

const isAPIDoc = (doc: Doc) => doc.attributes.pathname.startsWith("/docs/api/");

const topLevelOrder = new Map(
  docs
    .filter(doc => doc.attributes.level === 0 && !isAPIDoc(doc))
    .map(doc => [doc.attributes.pathname.split("/")[2], doc.attributes.order]),
);

const compareDocs = (a: Doc, b: Doc) => {
  const aSection = a.attributes.pathname.split("/")[2] ?? "";
  const bSection = b.attributes.pathname.split("/")[2] ?? "";
  const sectionOrder =
    (topLevelOrder.get(aSection) ?? Infinity) -
    (topLevelOrder.get(bSection) ?? Infinity);

  return (
    sectionOrder ||
    a.attributes.level - b.attributes.level ||
    a.attributes.order - b.attributes.order ||
    a.attributes.pathname.localeCompare(b.attributes.pathname)
  );
};

const compareAPIDocs = (a: Doc, b: Doc) => {
  const aParts = a.attributes.pathname
    .replace(/^\/docs\/api\/?|\/$/g, "")
    .split(".");
  const bParts = b.attributes.pathname
    .replace(/^\/docs\/api\/?|\/$/g, "")
    .split(".");

  return (
    (aParts[0] ?? "").localeCompare(bParts[0] ?? "") ||
    aParts.length - bParts.length ||
    a.attributes.pathname.localeCompare(b.attributes.pathname)
  );
};

const absoluteURL = (pathname: string) => new URL(pathname, baseURL).toString();

const punctuate = (value: string) =>
  /[.!?]$/.test(value.trim()) ? value.trim() : `${value.trim()}.`;

const extractTitle = (doc: Doc) =>
  doc.body.replace(/\r\n?/g, "\n").match(/^#{1,6}\s+(.+)$/m)?.[1] ??
  doc.attributes.title;

const rewriteRelativeLinks = (body: string, doc: Doc) => {
  const sourceBase = doc.attributes.index
    ? doc.attributes.pathname
    : doc.attributes.pathname.replace(/[^/]+\/$/, "");

  return body.replace(/\[([^\]]+)\]\(([^\s)]+)\)/g, (match, label, href) => {
    if (/^(?:[a-z]+:|#|\/)/i.test(href)) return match;

    const url = new URL(href, absoluteURL(sourceBase));
    if (url.pathname.endsWith(".csspropertyconflicts.md")) return label;

    url.pathname = url.pathname
      .replace(/\/index\.md$/, "/")
      .replace(/\.md$/, "/");
    return `[${label}](${url.toString()})`;
  });
};

const prepareBody = (doc: Doc) => {
  const title = extractTitle(doc);
  return rewriteRelativeLinks(doc.body.replace(/\r\n?/g, "\n"), doc)
    .replace(
      /^<!-- Do not edit this file\. It is automatically generated by API Documenter\. -->\r?\n+/,
      "",
    )
    .replace(/^\[Home\].*\r?\n+/m, "")
    .replace(new RegExp(`^#{1,6}\\s+${escapeRegExp(title)}\\s*$`, "m"), "")
    .replace(/^(#{1,5})(?=\s)/gm, "#$1")
    .trim();
};

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function createLlmsIndex() {
  const guides = docs
    .filter(
      doc =>
        !isAPIDoc(doc) && !doc.attributes.hidden && doc.attributes.order >= 0,
    )
    .sort(compareDocs)
    .map(
      doc =>
        `- [${doc.attributes.title}](${absoluteURL(doc.attributes.pathname)}): ${punctuate(doc.attributes.description)}`,
    );

  return [
    ...[
      "# CSS Hooks",
      "> CSS Hooks adds CSS selectors and at-rules to native inline styles, with no build step and minimal runtime.",
      "## Guides",
    ].flatMap(x => [x, ""]),
    ...guides,
    "",
    ...[
      "## API Reference",
      `- [CSS Hooks API](${absoluteURL("/docs/api/")}): Detailed reference for the core, React, Preact, Qwik, and Solid packages.`,
      "## Complete Documentation",
      `- [Full documentation](${absoluteURL("/llms-full.txt")}): All guides and API reference pages combined as Markdown.`,
      "",
    ].flatMap(x => [x, ""]),
  ].join("\n");
}

export function createLlmsFull() {
  const authoredDocs = docs.filter(doc => !isAPIDoc(doc)).sort(compareDocs);
  const apiDocs = docs.filter(isAPIDoc).sort(compareAPIDocs);

  const sections = [...authoredDocs, ...apiDocs].map(doc => {
    const title = extractTitle(doc);
    const body = prepareBody(doc);
    return [`## [${title}](${absoluteURL(doc.attributes.pathname)})`, "", body]
      .filter(Boolean)
      .join("\n");
  });

  return [
    ...[
      "# CSS Hooks Documentation",
      "> CSS Hooks adds CSS selectors and at-rules to native inline styles, with no build step and minimal runtime.",
      "This file is generated from the documentation source.",
    ].flatMap(x => [x, ""]),
    ...sections.flatMap((section, index) =>
      index === sections.length - 1 ? [section, ""] : [section, "", "---", ""],
    ),
  ].join("\n");
}
