packages:
  - "packages/core"
  - "packages/preact"
  - "packages/qwik"
  - "packages/react"
  - "packages/solid"
  - "examples/preact"
  - "examples/qwik"
  - "examples/react"
  - "examples/solid"
  - "site"
