/** @internal */
const types = [
  "active",
  "autofill",
  "checked",
  "default",
  "disabled",
  "empty",
  "enabled",
  "even-child",
  "first-child",
  "first-of-type",
  "focus",
  "focus-visible",
  "focus-within",
  "hover",
  "in-range",
  "indeterminate",
  "invalid",
  "last-child",
  "last-of-type",
  "odd-child",
  "only-child",
  "only-of-type",
  "out-of-range",
  "placeholder-shown",
  "read-only",
  "required",
  "target",
  "valid",
  "visited",
] as const;

export default types;
