name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wagoid/commitlint-github-action@v6

      - name: create nvmrc
        run: sed -n 's/^use-node-version=//p' .npmrc >> .nvmrc

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v3
        with:
          run_install: false

      - name: get pnpm store
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: pnpm cache
        env:
          STORE_PATH: ${{ env.STORE_PATH }}
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install

      - run: pnpm check

      - uses: browser-actions/setup-chrome@v1
        id: chrome

      - run: pnpm -r test
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}

      # Ensure docs are up-to-date.
      - run: |
          pnpm run docs
          if [[ -n $(git status --porcelain) ]]; then
            echo 'Error: Git status is not clean.';
            exit 1;
          fi

      - run: pnpm -r -F @examples/* build

      - run: pnpm run -r -F ./site build
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
