name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: wagoid/commitlint-github-action@v6

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - run: pnpm install

      - run: pnpm check

      - uses: browser-actions/setup-chrome@v1
        id: chrome

      - run: pnpm -r test
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}

      # Ensure docs are up-to-date.
      - run: |
          pnpm run docs
          if [[ -n $(git status --porcelain) ]]; then
            echo 'Error: Git status is not clean.';
            exit 1;
          fi

      - run: pnpm -r -F @examples/* build

      - run: pnpm run -r -F site build
        env:
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.chrome.outputs.chrome-path }}
