name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wagoid/commitlint-github-action@v6

      - name: create nvmrc
        run: sed -n 's/^use-node-version=//p' .npmrc >> .nvmrc

      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.4
          run_install: true

      - run: pnpm exec prettier --check .

      # Note that the packages must be built before linting. Otherwise, some
      # types will be inferred as `any` leading to errors.
      - run: pnpm run -r lint

      - run: pnpm -r test

      # Ensure docs are up-to-date.
      - run: |
          pnpm run docs
          if [[ -n $(git status --porcelain) ]]; then
            echo 'Error: Git status is not clean.';
            exit 1;
          fi

      - run: pnpm run -r --filter=./examples/* build

      - run: pnpm run -r --filter=./site build
