name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - if: github.event_name != 'pull_request'
        uses: wagoid/commitlint-github-action@v5

      - uses: actions/setup-node@v3
        with:
          node-version: 20.5.0
          registry-url: "https://registry.npmjs.org"

      - run: npm ci

      - run: npx prettier --check .

      # Note that the packages must be built before linting. Otherwise, some
      # types will be inferred as `any` leading to errors.
      - run: npm run lint --workspaces --if-present

      - run: npm test --workspaces --if-present

      # Ensure docs are up-to-date.
      - run: npm run docs
      - run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo 'Error: Git status is not clean.';
            exit 1;
          fi

      - run: npm run build --workspace=examples

      - run: npm run build --workspace=site
