name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: wagoid/commitlint-github-action@v5

      - id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key:
            ${{ runner.os }}-build-${{ env.cache-name }}-${{
            hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list

      - uses: actionsx/prettier@v3
        with:
          args: --check .

      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.1

      - run: npm ci

      - run: npm run prepublishOnly --workspaces --if-present

      # Note that linting must be done after the `prepublishOnly` scripts are
      # run. Otherwise, some types will be inferred as `any` leading to errors.
      - run: npm run lint --workspaces --if-present

      - run: npm test --workspaces --if-present

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: npm run build --workspace=site

      - if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/out
          cname: css-hooks.com
          commit_message: ${{ github.event.head_commit.message }}
