name: next

on:
  pull_request:
    types:
      - opened
      - synchronize
      - edited
      - reopened
    branches:
      - next

jobs:
  title:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          allowed_prefixes: "fix:,feat:,breaking:,misc:"
          prefix_case_sensitive: true
          regex: "^[A-Za-z\\s]+: \\S.*$"
          github_token: ${{ github.token }}

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
        with:
          configFile: .commitlintrc.json

  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npx prettier -c "**/*.{js,ts,tsx,json,md,yml}"

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npx eslint . --max-warnings=0

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run build --workspaces --if-present

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps chromium firefox webkit
      - run: npm test --workspaces --if-present
      - run: npm test --workspace=@css-hooks/core
        env:
          BROWSER: firefox
      - run: npm test --workspace=@css-hooks/core
        env:
          BROWSER: webkit

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run docs
      - name: check
        run: |
          if [[ -n $(git status --porcelain docs/api) ]]; then
            echo 'Error: API documentation is out of sync with code changes.'
            echo 'Please run "npm run docs" locally and commit the updated markdown files.'
            git status --porcelain docs/api
            exit 1
          fi

  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npm run codegen --workspaces --if-present
      - name: check
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo 'Error: Generated files are out of sync.'
            echo 'Please run "npm run codegen --workspaces --if-present" locally and commit the updated files.'
            git status --porcelain
            exit 1
          fi
