name: site

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run build -w site
      - uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_TOKEN }}
          accountId: ${{ vars.CF_ACCOUNT_ID }}
          command: >-
            pages deploy site/build/client --project-name=css-hooks
            --branch=${{ contains(github.ref_name, '-next.') && 'next' || 'latest' }}